[package]
name = "petal-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-display = "0.2.1"
petal-core = { path = "../petal-core" }
petal-lexer = { path = "../petal-lexer" }

[lib]
doctest = false
