name: Build and Test

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # https://github.com/TheDan64/inkwell/issues/490
    - name: Install dependencies
      run: |
        sudo apt install libpolly-18-dev
    - name: cc --verbose
      run: cc --verbose
    - name: gcc --verbose
      run: gcc --verbose
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: cargo build --verbose
    - name: Run Rust tests
      run: cargo test --verbose
    - name: Run compiler tests
      run: ./tests/test-runner.py
